# AUTO-GENERATED by `dragon ffi sync` from test_ffi_python.dr - DO NOT EDIT (always regenerated).
# signature: score(batch: list[User]) -> list[Scored]
import json
import struct
import sys
import traceback
from dataclasses import dataclass, asdict


@dataclass
class User:
    id: int
    tag: str


@dataclass
class Scored:
    id: int
    score: int


def _in_User(v):
    return User(id=v["id"], tag=v["tag"])


def _in_Scored(v):
    return Scored(id=v["id"], score=v["score"])


def _out(v):
    if isinstance(v, list):
        return [_out(x) for x in v]
    if hasattr(v, "__dataclass_fields__"):
        return asdict(v)
    return v


def _reply(header, payload=b""):
    sys.stdout.buffer.write(struct.pack("<I", len(header)) + header + payload)
    sys.stdout.buffer.flush()


def serve(fn):
    while True:
        pre = sys.stdin.buffer.read(4)
        if len(pre) < 4:
            return
        hlen = struct.unpack("<I", pre)[0]
        header = json.loads(sys.stdin.buffer.read(hlen))
        body = sys.stdin.buffer.read(header.get("body_len", 0))
        blobs = [sys.stdin.buffer.read(n) for n in header.get("blobs", [])]
        payload = json.loads(body) if body else {}
        try:
            result = fn(batch=[_in_User(e) for e in payload["batch"]])
        except Exception:
            err = traceback.format_exc().encode()
            _reply(json.dumps({"ok": False, "error_len": len(err)}).encode(), err)
            continue
        out = _out(result)
        if isinstance(out, (bytes, bytearray)):
            body_out = json.dumps({"$blob": 0}).encode()
            rh = json.dumps({"ok": True, "body_len": len(body_out), "blobs": [len(out)]}).encode()
            _reply(rh, body_out + bytes(out))
        else:
            body_out = json.dumps(out).encode()
            rh = json.dumps({"ok": True, "body_len": len(body_out), "blobs": []}).encode()
            _reply(rh, body_out)
